openapi: 3.0.0
info:
  title: testExample
  version: '3.0'
  description: My other description
  contact:
    name: Sarah
    email: hello@test.com
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: get users
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  address:
                    type: string
                  face:
                    type: string
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  address:
                    type: string
                  face:
                    type: string
      operationId: get-users
      description: Something
components:
  schemas: {}
  securitySchemes:
    hereIsAKey:
      name: API Key
      type: apiKey
      in: query
