openapi: 3.0.0
info:
  title: testExample
  version: '1.0'
  description: Hi I am a description
  contact:
    name: Sarah
    email: hello@test.com
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas: {}
